fos_user:
    db_driver:      orm 
    firewall_name:  main
    
    #profile:  # Authentication Form
     #   form:
     #       type:               fos_user_profile
     #       handler:            fos_user.profile.form.handler.default
     #       name:               fos_user_profile_form
     #       validation_groups:  [Authentication] # Please note : this is not the default value
    profile:
        form:
            type:   App\Application\FOSUser\Form\ProfileType
    
    user_class:     App\Application\Sonata\UserBundle\Entity\User
    
    registration:
        confirmation:
            enabled: true

    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: webmestre2@olymphys.fr
        sender_name: Webmestre2
