# config/packages/sonata.yaml

sonata_core:
    form:
        mapping:
            enabled: false
    form_type: horizontal
    
sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
    admin:
        user:
            class: App\Application\Sonata\UserBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
    #profile:  # Profile Form (firstname, lastname, etc ...)
    #    form:
    #        type:               sonata_user_profile
    #        handler:            sonata.user.profile.form.handler.default
    #        name:               sonata_user_profile_form
    #        validation_groups:  [Profile]
            
sonata_translation:
    locales: [en, fr, it, nl, es]
    default_locale: fr
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: true
    #phpcr:
    #    enabled: true
    
