<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ElevesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. cope coller
 */
class ElevesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEquipesEleves()
	{
		$query=$this->createQueryBuilder('e')
		->Join('e.equipeleves', 'k')
		->addSelect('k')
		->getQuery();

		return $query->getResult();
	}


}
