<?php

namespace App\Entity;
namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function MyFindOne($id)
	{
		$queryBuilder=$this->createQueryBuilder('e');  // e est un alias, un raccourci donné à l'entité du repository. 1ère lettre du nom de l'entité

		// On ajoute des critères de tri, etc. 
		$queryBuilder
			-> where('e.id=:id')
			->setParameter('id', $id);

		// on récupère la query 
		$query = $queryBuilder->getQuery();

		// on récupère les résultats à partir de la Query 
		$results=$query->getResult();

		// on retourne ces résultats
		return $results;
	}
	public function MyFindIdByLettre($lettre)
	{
		$queryBuilder=$this->createQueryBuilder('e');  // e est un alias, un raccourci donné à l'entité du repository. 1ère lettre du nom de l'entité

		// On ajoute des critères de tri, etc. 
		$queryBuilder
			->select('e.id')
			->where('e.lettre=:lettre')
				->setParameter('lettre', $lettre);

		// on récupère la query 
		$query = $queryBuilder->getQuery();

		// on récupère les résultats à partir de la Query 
		$value=$query->getSingleScalarResult();

		// on retourne ces résultats
		return $value;
	}

}
