<?php

namespace App\Repository;

/**
 * JuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuresRepository extends \Doctrine\ORM\EntityRepository
{
}
