core_home:
    path: /
    controller: App\Controller\CoreController:index
    
cyberjury_accueil:
    path: cyberjury/accueil
    controller: App\Controller\JuryController:accueil
    
cyberjury_evaluer_une_equipe:
    path:     /evaluer_une_equipe/{id}
    defaults: { _controller: App\Controller\JuryController:evaluer_une_equipe }
    requirements: 
        id_equipe : \d{1}|\d{2}   
        
cyberjury_infos_equipe:
    path:     /infos_equipe/{id}
    defaults: { _controller: App\Controller\JuryController:infos_equipe }
    requirements: 
        id_equipe : \d{1}|\d{2}
        
cyberjury_tableau_de_bord:
     path:     /tableau_de_bord
     defaults: { _controller: App\Controller\JuryController:tableau }


cyberjury_phrases_amusantes:
    path:     /phrases_amusantes/{id}
    defaults: { _controller: App\Controller\JuryController:phrases }
    requirements: 
        id_equipe : \d{1}|\d{2}  
     
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

