<?php

namespace App\Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */

/**
 * User
 *
 * @ORM\Table(name="fos_user_user")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="rne", type="string", length=255, nullable=true)
     */
    protected $rne;

        /**
     * @var string
     *
     * @ORM\Column(name="adresse", type="string", length=255, nullable=true)
     */
    protected $adresse;
        /**
     * @var string
     *
     * @ORM\Column(name="ville", type="string", length=255, nullable=true)
     */
    protected $ville;
        /**
     * @var integer
     *
     * @ORM\Column(name="code", type="integer", length=11, nullable=true)
     */
    protected $code;
    /**
     * Set rne
     *
     * @param string $rne
     *
     * @return User
     */
    public function setRne( $rne) {
        $this->rne= $rne;

        return $this;
    }

    /**
     * Get Adresse
     *
     * @return string
     */
    public function getAdresse() {
        return $this->adresse;
    }
    /**
     * Set adresse
     *
     * @param string $adresse
     *
     * @return User
     */
    public function setAdresse( $adresse) {
        $this->adresse= $adresse;

        return $this;
    }

    /**
     * Get ville
     *
     * @return string
     */
    public function getVille() {
        return $this->ville;
    }
    /**
     * Set ville
     *
     * @param string $ville
     *
     * @return User
     */
    public function setVille( $ville) {
        $this->ville= $ville;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode() {
        return $this->code;
    }
    /**
     * Set Code
     *
     * @param string $code
     *
     * @return User
     */
    public function setCode( $code) {
        $this->code= $code;

        return $this;
    }

    /**
     * Get rne
     *
     * @return string
     */
    public function getRne() {
        return $this->rne;
    }


    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
